config/routes.rb
Rails.application.routes.draw do

  resources :charges
  resource :shopping_cart

  resources :carts
  devise_for :users
  resources :users
  root 'welcome#index'
  resources :categories
  resources :products do
    member do
      get 'add_pictures'
      patch 'create_picture'
    end
  end
  resources :pictures

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products
  has_many :pictures, through: :products

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :s3picture, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :s3picture, :content_type => /\Aimage\/.*\Z/
  belongs_to :product
  belongs_to :category
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures
end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  acts_as_shopping_cart
end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ActiveRecord::Base
  acts_as_shopping_cart_item
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @category = Category.new
    @categories = Category.all

    @user = User.new
    @users = User.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit
  protect_from_forgery

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(set_params)
    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    Category.update(params[:id], set_params)
    redirect_to categories_path
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products
  end

  def destroy
    Category.find(params[:id]).destroy
  end

  private

  def set_params
    params.require(:category).permit(:name)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @shopping_cart = ShoppingCart.find(session[:shopping_cart_id])
  end

  def create
    # Amount in cents
    @shopping_cart = ShoppingCart.find(session[:shopping_cart_id])
    @amount = (@shopping_cart.total * 100).to_i

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.save
  end

  def edit
  end

  def update
  end

  def show
    @picture = Picture.new(picture_params)
  end

  def index
    @pictures = Picture.all
  end

  def destroy
    @picture = Picture.find(params[:id]).destroy!
    redirect_to pictures_path
  end

private

  def picture_params
    params.require(:picture).permit(:id, :alt, :picture_url, :s3picture)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  respond_to :js, :html

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    authorize @product
    @categories = Category.all.map {|category| [category.name, category.id]}
  end

  def create
    @product = Product.new(set_params)
    authorize @product
    @product.save
    redirect_to add_pictures_product_path(@product)
  end

  def add_pictures
    @product = Product.find(params[:id])
  end

  def create_picture
    # @product = Product.find(params[:id])
    # @product.update(set_params)
    # redirect_to product_path(@product)
    @product = Product.find(params[:id])
    @product.pictures.create(picture_params)
  end

  def edit
    @categories = Category.all.map {|category| [category.name, category.id]}
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(set_params)
    redirect_to product_path(@product)
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    authorize @product
    flash[:info] = "you have deleted #{@product.name}"
    @product.destroy
    redirect_to categories_path
  end

  private

  def set_params
    params.require(:product).permit(:name, :category_id, :description, :localization, :quantity, :price, :user_id)
  end

  def picture_params
    authorize @product
    params.require(:product).permit(:s3picture)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/charges/create.html.erb
<p class="lead">Thanks, your payment of <strong><%= @amount %>€</strong> has been proceeded. You should receive your package soon :)</p>

<%= link_to "Can't have enough shopping ? Go find some more great products", categories_path %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <h2>You are about to check out your cart</h2>
    <label class="amount">
      <span>Total amount: <%= @shopping_cart.total %>€</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-name="Itsy"
          data-description="Please enter your credit card infos"
          data-amount= <%= (@shopping_cart.total*100).to_s %>
          data-image="http://i.imgur.com/VpRRuwF.png"
          data-currency="EUR"
          data-panel-label="Pay {{amount}}"
          data-label="Finish payment">
  </script>
<% end %>

app/views/welcome/index.html.erb
<div class="container welcomepage">

  <div class="row welcome">
    <div class="welcometext col-xs-10 col-xs-offset-1">
          <div class="pull-right">
            <h1>Le premier marché artisanal du village global !</h1>
          </div>
          <div class="pull-right">
            <p class="links"><nobr><%= link_to "View our Categories ", categories_path %> or <%= link_to  "Add a new Product", products_path %></nobr></p>
          </div>
          <div class="pull-left">
             <p>  We currently have <%= pluralize(User.all.size, 'user')%> selling <%= pluralize(Product.all.size, 'amazing product')%> !</p>
          </div>
    </div>
  </div>
  <div id="footer">
    <div class="container">

      </p>
    </div>
  </div>
</div>