config/routes.rb
Rails.application.routes.draw do

  resources :charges
  resource :shopping_cart

  resources :carts
  devise_for :users
  resources :users
  root 'welcome#index'
  resources :categories
  resources :products do
    member do
      get 'add_pictures'
      patch 'create_picture'
    end
  end
  resources :pictures

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products
  has_many :pictures, through: :products

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :s3picture, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :s3picture, :content_type => /\Aimage\/.*\Z/
  belongs_to :product
  belongs_to :category
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures
end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  acts_as_shopping_cart
end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ActiveRecord::Base
  acts_as_shopping_cart_item
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @category = Category.new
    @categories = Category.all

    @user = User.new
    @users = User.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit
  protect_from_forgery

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(set_params)
    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    Category.update(params[:id], set_params)
    redirect_to categories_path
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products
  end

  def destroy
    Category.find(params[:id]).destroy
  end

  private

  def set_params
    params.require(:category).permit(:name)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @shopping_cart = ShoppingCart.find(session[:shopping_cart_id])
  end

  def create
    # Amount in cents
    @shopping_cart = ShoppingCart.find(session[:shopping_cart_id])
    @amount = (@shopping_cart.total * 100).to_i

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.save
  end

  def edit
  end

  def update
  end

  def show
    @picture = Picture.new(picture_params)
  end

  def index
    @pictures = Picture.all
  end

  def destroy
    @picture = Picture.find(params[:id]).destroy!
    redirect_to pictures_path
  end

private

  def picture_params
    params.require(:picture).permit(:id, :alt, :picture_url, :s3picture)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  respond_to :js, :html

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    authorize @product
    @categories = Category.all.map {|category| [category.name, category.id]}
  end

  def create
    @product = Product.new(set_params)
    authorize @product
    @product.save
    redirect_to add_pictures_product_path(@product)
  end

  def add_pictures
    @product = Product.find(params[:id])
  end

  def create_picture
    # @product = Product.find(params[:id])
    # @product.update(set_params)
    # redirect_to product_path(@product)
    @product = Product.find(params[:id])
    @product.pictures.create(picture_params)
  end

  def edit
    @categories = Category.all.map {|category| [category.name, category.id]}
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(set_params)
    redirect_to product_path(@product)
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    authorize @product
    flash[:info] = "you have deleted #{@product.name}"
    @product.destroy
    redirect_to categories_path
  end

  private

  def set_params
    params.require(:product).permit(:name, :category_id, :description, :localization, :quantity, :price, :user_id)
  end

  def picture_params
    authorize @product
    params.require(:product).permit(:s3picture)
  end

end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController

  before_action :extract_shopping_cart


  def create
    # first creates a shopping cart (cf before_action), then adds the product
    @product = Product.find(params[:product_id])
    @shopping_cart.add(@product, @product.price)
    redirect_to shopping_cart_path
  end

  def show
  end

  def destroy
    @shopping_cart.shopping_cart_items.find(params[:product_id]).destroy
    redirect_to shopping_cart_path
  end

  private

  def extract_shopping_cart
    if session[:shopping_cart_id]
      @shopping_cart = ShoppingCart.find(session[:shopping_cart_id])
    else
      @shopping_cart = ShoppingCart.create
      session[:shopping_cart_id] = @shopping_cart.id
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit the category <%= @category.name %></h1>

<%= render "form" %>

app/views/categories/index.html.erb
<div class="flash-box"><%= flash[:info] %></div>
<div class="container">
  <% @categories.each do |category| %>
    <% if(@categories.first == category || @categories[6] == category) %>
      <div class="col-md-8 col-sm-6">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h2 class="panel-title"><%= link_to category.name.capitalize, category_path(category) %>
           <a href=<%= category_path(category) %>><span class="glyphicon glyphicon-chevron-right pull-right"></span></a></h2>
        </div>
          <div class="panel-body">
            <% unless category.products.first == nil %>
              <% if category.products.first.pictures.size > 0 %>
                <%= link_to (image_tag category.products.first.pictures.first.s3picture.url(:medium)), product_path(category.products.first) %>
              <% end %>
            <% end %>
            <div class="text-right"><%= link_to(category.products.length.to_s + " products", category_path(category))%></div>
          </div>
      </div>
    </div>
    <% elsif %>
      <div class="col-md-4 col-sm-6">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h2 class="panel-title"><%= link_to category.name.capitalize, category_path(category) %><a href=<%= category_path(category) %>><span class="glyphicon glyphicon-chevron-right pull-right"></span></a></h2>
          </div>
            <div class="panel-body">
              <div class="text-right"><%= link_to(category.products.length.to_s + " products", category_path(category))%></div>
            </div>
        </div>
      </div>
    <% end %>
  <% end %>

</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form" %>

app/views/categories/show.html.erb
<div class="container">

  <div class="page-header">
    <h1 class="text-center"><%= @category.name.capitalize %></h1>
    <h1 class="text-right"><small><%= @products.length %> products</small></h1>
  </div>

    <% @products.each do |product| %>

      <div class="col-md-4 col-sm-6">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h2 class="panel-title"><%= link_to product.name.capitalize, product_path(product) %> <span class="pull-right">
              <% if product.price % 1 == 0 %>
                <%= product.price.to_i %>
              <% else %>
                <%= product.price %>
              <% end %>
               €</span></h2>
          </div>
            <div class="panel-body">
              <div>
                <% if product.pictures.size > 0 %>
                  <%= link_to((image_tag product.pictures.first.s3picture.url(:medium)), product_path(product)) %>
                <% end %>
              </div>
            </div>
        </div>
      </div>

    <% end %>

</div>

app/views/pictures/_form.html.erb
<%= form_for(@picture, :html => { :multipart => true }) do |f| %>

<div class="field">
  <%= f.label :picture %><br>
  <%= f.file_field :s3picture %>
</div>
<div class="actions">
 <%= f.submit %>
</div>
<% end %>

app/views/pictures/create.html.erb
<h1>Your picture has been successfully uploaded</h1>
<div>
  <%= image_tag @picture.s3picture.url(:medium) %>
</div>

app/views/pictures/destroy.html.erb
<h1>Pictures#destroy</h1>
<p>Find me in app/views/pictures/destroy.html.erb</p>

app/views/pictures/edit.html.erb
<h1>You can now change the picture</h1>

app/views/pictures/index.html.erb
<h1>Pictures index</h1>
  Pictures array is <%= @pictures.size %> long.
  <% @pictures.each do |picture| %>
      <div>
      <%= picture.id %>
    </div>
    <div>
      <%= image_tag picture.s3picture.url(:medium) %>
    </div>
    <div>
      <%= link_to 'Delete', picture_path(picture), method: :delete %>
    </div>
  <% end %>

app/views/pictures/new.html.erb
<h1>Upload your file</h1>
<%= render "form" %>

app/views/pictures/show.html.erb
<%= image_tag @picture.picture.url(:medium) %>

<%= link_to "Delete image", picture_path(@picture), method: :delete %>
<%= link_to "Change image", edit_picture_path(@picture) %>

app/views/pictures/update.html.erb
<h1>Pictures#update</h1>
<p>Find me in app/views/pictures/update.html.erb</p>

app/views/products/_form.html.erb
<div class="form-container col-sm-12">
  <%= form_for @product do |f| %>
    <div class="form-group form-name">
      <div><%= f.label :name, "Name of your product" %></div>
      <div><%= f.text_field :name, required: true, class: "form-control" %></div>
    </div>
    <div class="form-group form-category">
      <div><%= f.label :category_id %></div>
      <div><%= f.select(:category_id, options_for_select(@categories), {}, {class: "form-control"}) %></div>
    </div>
    <div class="form-group form-price">
      <div><%= f.label :price %></div>
      <div id="price-input"><%= f.number_field :price, required: true, class: "form-control", placeholder: "€" %></div>
    </div>
    <div class="form-group">
      <div><%= f.label :quantity, "How many products can you sell ?" %></div>
      <div class="form-quantity"><%= f.number_field :quantity, required: true, class: "form-control" %></div>
    </div>
    <div class="form-group form-localization">
      <div><%= f.label :localization, "Where are you from?" %></div>
      <div><%= f.text_field :localization, required: true, class: "form-control" %></div>
    </div>
    <div class="form-group">
      <div><%= f.label :description, "Describe briefly your product" %></div>
      <div><%= f.text_area(:description, required: true, cols: 50, rows: 10, class: "form-control") %></div>
    </div>
    <div><%= f.hidden_field :user_id, value: current_user.id %></div>
    <div><%= f.submit class: "btn btn-lg btn-primary" %></div>
  <% end %>
</div>

app/views/products/_form_pics.html.erb
<p class="lead">Please add pictures to <%=@product.name%></p>

<%= form_for @product, :url => { :controller => "products", :action => "create_picture" }, :html => { :multipart => true }, :remote => true do |f| %>
  <div><%= f.file_field :s3picture, class: "upload" %></div>
  <div id="pictures-container">
    <%= render 'pictures' %>
  </div>
<% end %>

app/views/products/_pictures.html.erb
    <h4><% if @product.pictures.size == 1 %>
          There is one picture.
        <% elsif @product.pictures.size == 0 %>
          There is no picture yet.
        <% else %>
          There are <%= @product.pictures.size %> pictures.
        <% end %>
    <%= link_to "When you're done go discover your great product page.", product_path(@product) %>
  </h4>

  <% @product.pictures.each do |picture| %>
    <fieldset>
      <%= image_tag picture.s3picture.url(:medium) %>
      <%= link_to "Delete", picture_path(picture), class: 'delete-picture', method: :delete, remote: true %>
    </fieldset>
  <% end %>

app/views/products/add_pictures.html.erb
<%= render "form_pics" %>

app/views/products/create_picture.js.erb
$('#pictures-container').html("<%= j render 'pictures' %>")

app/views/products/edit.html.erb
<h1>You can now change the product</h1>

<%= render "form" %>

app/views/products/index.html.erb
<h1>Products index</h1>

<table>
   <thead>
  <tr>
     <th>Product name</th>
     <th>Price</th>
     <th>Localization</th>
     <th>Quantity left</th>
     <th>Description</th>
  </tr>
 </thead>
  <% @products.each do |product| %>
    <tr>
      <% if product.pictures.size > 0 %>
        <td><%= image_tag product.pictures.first.s3picture_url, size: "200x300", alt: product.pictures.first.alt%></td>
      <% end %>
      <td><%= link_to(product.name, product_path(product))%></td>
      <td><% if product.price % 1 == 0 %>
                <%= product.price.to_i %>
              <% else %>
                <%= product.price %>
              <% end %> €</td>
      <td><%= product.localization %></td>
      <td><%= product.quantity %></td>
      <td><%= truncate(product.description, length: 30) %></td>
    </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<div class="container">
  <div class="row">
    <p class="lead">Add a new product on Itsy</p>
    <hr>
  </div>
    <%= render "form" %>
</div>

app/views/products/show.html.erb
<div class="container">

<div class="row">
  <div class="col-sm-7">
    <h1 class="product-title"><%= @product.name.capitalize %></h1>
    <% if policy(@product).update? %>
      Edit <%= link_to "product details", edit_product_path(@product) %>,
      <%= link_to "pictures", add_pictures_product_path(@product) %>
    <% end %>
    <% if policy(@product).destroy? %>
        or <%= link_to "delete product", product_path(@product), method: 'delete' %>
      <% end %>
  </div>
  <div class="col-sm-5">
    <div class="pull-right"><%= button_to "Go back to the products list" , category_path(@product.category), method: :get, class: 'btn btn-info' %>
    </div>
  </div>
</div>
<hr>

  <div class="row">
    <div class="col-sm-7">
      <% if @product.pictures.size > 0 %>
        <% @product.pictures.each do |picture| %>
          <%= image_tag picture.s3picture.url(:medium), class: 'align' %>
        <% end %>
      <% end %>
    </div>
    <div class="col-sm-5">
      <div class="panel panel-info pull-right panel-width">
        <div class="panel-heading">
          <div class="panel-title">
            <p class="lead no-margin-bottom text-center">Price :
            <strong>
            <% if @product.price % 1 == 0 %>
              <%= @product.price.to_i %>
            <% else %>
              <%= @product.price %>
            <% end %> €
            </strong>
            </p>
          </div>
        </div>
      <div class="panel-body">
        <% unless @product.user_id == nil %>
          <p class="user-infos">Added by <%= link_to User.find(@product.user_id).email, user_path(User.find(@product.user_id))%></p>
        <% end %>
        <p>Localization : <%= @product.localization %></p>
        <p>Added on <%= @product.created_at.to_date %></p>
        <div class="text-center">
          <hr>
        <%= button_to "Add to cart", shopping_cart_path(product_id: @product), :class => "btn btn-lg btn-success", method: 'POST' %>
        </div>
      </div>
    </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10">
      <p><strong>Description:</strong> <em><%= @product.description %></em></p>
    </div>
  </div>
</div>

app/views/products/update.js.erb
$('#pictures-container').html("<%= j render 'pictures' %>")

app/views/shopping_carts/show.html.erb
<div class="container">
  <div class="cart-container">
  <% if @shopping_cart.shopping_cart_items.length > 0 %>
    <div class="row">
      <div class="col-sm-6">
        <p class="lead">Your cart has <strong><%= pluralize(@shopping_cart.shopping_cart_items.length, 'product') %></strong></p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
      <table class="table table-hover cart-table">
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th></th>
      <% total = 0 %>
      <% @shopping_cart.shopping_cart_items.each do |product| %>
        <tr>
          <td>
            <%= link_to Product.find(product.item_id).name.capitalize, product_path(Product.find(product.item_id)) %>
          </td>
          <td>
            <%= product.price %> €
          </td>
          <td>
            <%= product.quantity %>
          </td>
          <td>
            <div class="pull-right"><%= button_to "Remove from my cart", shopping_cart_path(product_id: product), method: :delete, class: 'btn btn-sm btn-danger' %></div>
          </td>
        </tr>
          <% total += (product.price * product.quantity) %>
      <% end %>
      </table>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4 pull-right">
        <h4 class="text-right">Total: <%=total%> €</h4>
      </div>
    </div>
    <div class="row checkout-btn">
      <div class="col-sm-5"><%= button_to "Go back shopping", categories_path, class: "btn btn-info", method: :get %></div>
      <div class="col-sm-5 pull-right"><%= button_to "I'm done! Checkout", new_charge_path(@shopping_cart.id), class: "btn btn-lg btn-success pull-right", method: :get %></div>
    </div>
    </div>
  <% else %>
    <h3>Your cart is empty :(</h3>
    <div class="shopping-frenzy">
      <%= button_to "Why not go on a shopping frenzy?", categories_path, method: :get, class: 'btn btn-lg btn-info' %>
    </div>
  <% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container">

  <div class="row">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title"><%= @user.name %>
          <% if @user.admin %>
            (Admin)
          <% else %>
            (Regular user)
          <% end %>
        </h2>
      </div>
      <div class="panel-body">
          <p>Email adress: <%= @user.email %></p>
          <p>Account created on <%= @user.created_at %></p>
          <p>Last sign on <%= @user.last_sign_in_at %></p>
      </div>
    </div>
  <% if @user.products.size > 0 %>
    <h3>Your products:</h3>
    <table class="table table-hover">
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th></th>
    <% @user.products.each do |product| %>
      <tr>
        <td>
          <%= link_to product.name, product_path(product) %>
        </td>
        <td>
          <%= product.price %>
        </td>
        <td>
          <%= product.description %>
        </td>
        <td>
          <%= link_to 'Edit product', edit_product_path(product) %>
        </td>
      </tr>
    <% end %>
  <% end %>

</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>